name: Sell
api: 2.0.0
main: Muqsit\Main
version: 1.1
permission:
  sell:
    default: op
    children:
      sell.hand:
        default: op
commands:
  sell:
    description: Sells the item in your hand!
