name: Sell
api: [3.0.0-ALPHA10]
main: SellHand\Main
version: 3.0
author: Muqsit
authors: [KairusDarkSeeker, Zeao]
commands:
  sell:
    description: "§bSells the item in your hand or all of your inventory's contents"
    permission: sell.command
permissions:
  sell:
    default: true
    children:
      sell.hand:
        default: true
      sell.all:
        default: false
      sell.command:
        default: true
